# Generated by Django 5.1 on 2024-09-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_company_user_is_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_company_owner',
            new_name='is_manager',
        ),
    ]
