# Generated by Django 5.0.7 on 2024-08-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitment', '0002_alter_job_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applied_candidates',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_recruitment.resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='resumes',
            field=models.ManyToManyField(through='job_recruitment.Application', to='job_recruitment.resume'),
        ),
    ]
