# Generated by Django 5.0.7 on 2024-08-26 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitment', '0003_remove_application_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
